//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bnhp.Office365.References {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="https://www.bankhapoalim.co.il/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bnhp.Office365.References.EMailMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bnhp.Office365.References.Appointment))]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateTimeCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateTimeReceivedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateTimeSentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayCcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Bnhp.Office365.References.ExtendedProperty[] ExtendedPropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Bnhp.Office365.References.Importance ImportanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsUnmodifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastModifiedNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastModifiedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Bnhp.Office365.References.Sensitivity SensitivityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextBodyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateTimeCreated {
            get {
                return this.DateTimeCreatedField;
            }
            set {
                if ((this.DateTimeCreatedField.Equals(value) != true)) {
                    this.DateTimeCreatedField = value;
                    this.RaisePropertyChanged("DateTimeCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateTimeReceived {
            get {
                return this.DateTimeReceivedField;
            }
            set {
                if ((this.DateTimeReceivedField.Equals(value) != true)) {
                    this.DateTimeReceivedField = value;
                    this.RaisePropertyChanged("DateTimeReceived");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateTimeSent {
            get {
                return this.DateTimeSentField;
            }
            set {
                if ((this.DateTimeSentField.Equals(value) != true)) {
                    this.DateTimeSentField = value;
                    this.RaisePropertyChanged("DateTimeSent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayCc {
            get {
                return this.DisplayCcField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayCcField, value) != true)) {
                    this.DisplayCcField = value;
                    this.RaisePropertyChanged("DisplayCc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayTo {
            get {
                return this.DisplayToField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayToField, value) != true)) {
                    this.DisplayToField = value;
                    this.RaisePropertyChanged("DisplayTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Bnhp.Office365.References.ExtendedProperty[] ExtendedProperties {
            get {
                return this.ExtendedPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtendedPropertiesField, value) != true)) {
                    this.ExtendedPropertiesField = value;
                    this.RaisePropertyChanged("ExtendedProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Bnhp.Office365.References.Importance Importance {
            get {
                return this.ImportanceField;
            }
            set {
                if ((this.ImportanceField.Equals(value) != true)) {
                    this.ImportanceField = value;
                    this.RaisePropertyChanged("Importance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsUnmodified {
            get {
                return this.IsUnmodifiedField;
            }
            set {
                if ((this.IsUnmodifiedField.Equals(value) != true)) {
                    this.IsUnmodifiedField = value;
                    this.RaisePropertyChanged("IsUnmodified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastModifiedName {
            get {
                return this.LastModifiedNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastModifiedNameField, value) != true)) {
                    this.LastModifiedNameField = value;
                    this.RaisePropertyChanged("LastModifiedName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastModifiedTime {
            get {
                return this.LastModifiedTimeField;
            }
            set {
                if ((this.LastModifiedTimeField.Equals(value) != true)) {
                    this.LastModifiedTimeField = value;
                    this.RaisePropertyChanged("LastModifiedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Bnhp.Office365.References.Sensitivity Sensitivity {
            get {
                return this.SensitivityField;
            }
            set {
                if ((this.SensitivityField.Equals(value) != true)) {
                    this.SensitivityField = value;
                    this.RaisePropertyChanged("Sensitivity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextBody {
            get {
                return this.TextBodyField;
            }
            set {
                if ((object.ReferenceEquals(this.TextBodyField, value) != true)) {
                    this.TextBodyField = value;
                    this.RaisePropertyChanged("TextBody");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EMailMessage", Namespace="https://www.bankhapoalim.co.il/")]
    [System.SerializableAttribute()]
    public partial class EMailMessage : Bnhp.Office365.References.Item {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Bnhp.Office365.References.Attachment[] AttachmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Bnhp.Office365.References.EMailAddress[] BccRecipientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Bnhp.Office365.References.EMailAddress[] CcRecipientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Bnhp.Office365.References.EMailAddress FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeliveryReceiptRequestedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReadReceiptRequestedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsResponseRequestedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Bnhp.Office365.References.EMailAddress SenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Bnhp.Office365.References.EMailAddress[] ToRecipientsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Bnhp.Office365.References.Attachment[] Attachments {
            get {
                return this.AttachmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentsField, value) != true)) {
                    this.AttachmentsField = value;
                    this.RaisePropertyChanged("Attachments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Bnhp.Office365.References.EMailAddress[] BccRecipients {
            get {
                return this.BccRecipientsField;
            }
            set {
                if ((object.ReferenceEquals(this.BccRecipientsField, value) != true)) {
                    this.BccRecipientsField = value;
                    this.RaisePropertyChanged("BccRecipients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Bnhp.Office365.References.EMailAddress[] CcRecipients {
            get {
                return this.CcRecipientsField;
            }
            set {
                if ((object.ReferenceEquals(this.CcRecipientsField, value) != true)) {
                    this.CcRecipientsField = value;
                    this.RaisePropertyChanged("CcRecipients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Bnhp.Office365.References.EMailAddress From {
            get {
                return this.FromField;
            }
            set {
                if ((object.ReferenceEquals(this.FromField, value) != true)) {
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeliveryReceiptRequested {
            get {
                return this.IsDeliveryReceiptRequestedField;
            }
            set {
                if ((this.IsDeliveryReceiptRequestedField.Equals(value) != true)) {
                    this.IsDeliveryReceiptRequestedField = value;
                    this.RaisePropertyChanged("IsDeliveryReceiptRequested");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRead {
            get {
                return this.IsReadField;
            }
            set {
                if ((this.IsReadField.Equals(value) != true)) {
                    this.IsReadField = value;
                    this.RaisePropertyChanged("IsRead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsReadReceiptRequested {
            get {
                return this.IsReadReceiptRequestedField;
            }
            set {
                if ((this.IsReadReceiptRequestedField.Equals(value) != true)) {
                    this.IsReadReceiptRequestedField = value;
                    this.RaisePropertyChanged("IsReadReceiptRequested");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsResponseRequested {
            get {
                return this.IsResponseRequestedField;
            }
            set {
                if ((this.IsResponseRequestedField.Equals(value) != true)) {
                    this.IsResponseRequestedField = value;
                    this.RaisePropertyChanged("IsResponseRequested");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Bnhp.Office365.References.EMailAddress Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Bnhp.Office365.References.EMailAddress[] ToRecipients {
            get {
                return this.ToRecipientsField;
            }
            set {
                if ((object.ReferenceEquals(this.ToRecipientsField, value) != true)) {
                    this.ToRecipientsField = value;
                    this.RaisePropertyChanged("ToRecipients");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Appointment", Namespace="https://www.bankhapoalim.co.il/")]
    [System.SerializableAttribute()]
    public partial class Appointment : Bnhp.Office365.References.Item {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowNewTimeProposalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> AppointmentReplyTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AppointmentSequenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AppointmentStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AppointmentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ConferenceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnhancedLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Bnhp.Office365.References.OccurrenceInfo FirstOccurrenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ICalDateTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ICalRecurrenceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ICalUidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAllDayEventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCancelledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMeetingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOnlineMeetingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRecurringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsResponseRequestedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JoinOnlineMeetingUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Bnhp.Office365.References.OccurrenceInfo LastOccurrenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MeetingRequestWasSentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeetingWorkspaceUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Bnhp.Office365.References.MeetingResponseType MyResponseTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NetShowUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Bnhp.Office365.References.Attendee[] OptionalAttendeesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Bnhp.Office365.References.Attendee OrganizerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OriginalStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Bnhp.Office365.References.Recurrence RecurrenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReminderMinutesBeforeStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Bnhp.Office365.References.Attendee[] RequiredAttendeesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Bnhp.Office365.References.Attendee[] ResourcesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> RetentionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeZoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowNewTimeProposal {
            get {
                return this.AllowNewTimeProposalField;
            }
            set {
                if ((this.AllowNewTimeProposalField.Equals(value) != true)) {
                    this.AllowNewTimeProposalField = value;
                    this.RaisePropertyChanged("AllowNewTimeProposal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AppointmentReplyTime {
            get {
                return this.AppointmentReplyTimeField;
            }
            set {
                if ((this.AppointmentReplyTimeField.Equals(value) != true)) {
                    this.AppointmentReplyTimeField = value;
                    this.RaisePropertyChanged("AppointmentReplyTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AppointmentSequenceNumber {
            get {
                return this.AppointmentSequenceNumberField;
            }
            set {
                if ((this.AppointmentSequenceNumberField.Equals(value) != true)) {
                    this.AppointmentSequenceNumberField = value;
                    this.RaisePropertyChanged("AppointmentSequenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AppointmentState {
            get {
                return this.AppointmentStateField;
            }
            set {
                if ((this.AppointmentStateField.Equals(value) != true)) {
                    this.AppointmentStateField = value;
                    this.RaisePropertyChanged("AppointmentState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AppointmentType {
            get {
                return this.AppointmentTypeField;
            }
            set {
                if ((this.AppointmentTypeField.Equals(value) != true)) {
                    this.AppointmentTypeField = value;
                    this.RaisePropertyChanged("AppointmentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConferenceType {
            get {
                return this.ConferenceTypeField;
            }
            set {
                if ((this.ConferenceTypeField.Equals(value) != true)) {
                    this.ConferenceTypeField = value;
                    this.RaisePropertyChanged("ConferenceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime End {
            get {
                return this.EndField;
            }
            set {
                if ((this.EndField.Equals(value) != true)) {
                    this.EndField = value;
                    this.RaisePropertyChanged("End");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnhancedLocation {
            get {
                return this.EnhancedLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.EnhancedLocationField, value) != true)) {
                    this.EnhancedLocationField = value;
                    this.RaisePropertyChanged("EnhancedLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Bnhp.Office365.References.OccurrenceInfo FirstOccurrence {
            get {
                return this.FirstOccurrenceField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstOccurrenceField, value) != true)) {
                    this.FirstOccurrenceField = value;
                    this.RaisePropertyChanged("FirstOccurrence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ICalDateTimeStamp {
            get {
                return this.ICalDateTimeStampField;
            }
            set {
                if ((this.ICalDateTimeStampField.Equals(value) != true)) {
                    this.ICalDateTimeStampField = value;
                    this.RaisePropertyChanged("ICalDateTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ICalRecurrenceId {
            get {
                return this.ICalRecurrenceIdField;
            }
            set {
                if ((this.ICalRecurrenceIdField.Equals(value) != true)) {
                    this.ICalRecurrenceIdField = value;
                    this.RaisePropertyChanged("ICalRecurrenceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ICalUid {
            get {
                return this.ICalUidField;
            }
            set {
                if ((object.ReferenceEquals(this.ICalUidField, value) != true)) {
                    this.ICalUidField = value;
                    this.RaisePropertyChanged("ICalUid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAllDayEvent {
            get {
                return this.IsAllDayEventField;
            }
            set {
                if ((this.IsAllDayEventField.Equals(value) != true)) {
                    this.IsAllDayEventField = value;
                    this.RaisePropertyChanged("IsAllDayEvent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCancelled {
            get {
                return this.IsCancelledField;
            }
            set {
                if ((this.IsCancelledField.Equals(value) != true)) {
                    this.IsCancelledField = value;
                    this.RaisePropertyChanged("IsCancelled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMeeting {
            get {
                return this.IsMeetingField;
            }
            set {
                if ((this.IsMeetingField.Equals(value) != true)) {
                    this.IsMeetingField = value;
                    this.RaisePropertyChanged("IsMeeting");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOnlineMeeting {
            get {
                return this.IsOnlineMeetingField;
            }
            set {
                if ((this.IsOnlineMeetingField.Equals(value) != true)) {
                    this.IsOnlineMeetingField = value;
                    this.RaisePropertyChanged("IsOnlineMeeting");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRecurring {
            get {
                return this.IsRecurringField;
            }
            set {
                if ((this.IsRecurringField.Equals(value) != true)) {
                    this.IsRecurringField = value;
                    this.RaisePropertyChanged("IsRecurring");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsResponseRequested {
            get {
                return this.IsResponseRequestedField;
            }
            set {
                if ((this.IsResponseRequestedField.Equals(value) != true)) {
                    this.IsResponseRequestedField = value;
                    this.RaisePropertyChanged("IsResponseRequested");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JoinOnlineMeetingUrl {
            get {
                return this.JoinOnlineMeetingUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.JoinOnlineMeetingUrlField, value) != true)) {
                    this.JoinOnlineMeetingUrlField = value;
                    this.RaisePropertyChanged("JoinOnlineMeetingUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Bnhp.Office365.References.OccurrenceInfo LastOccurrence {
            get {
                return this.LastOccurrenceField;
            }
            set {
                if ((object.ReferenceEquals(this.LastOccurrenceField, value) != true)) {
                    this.LastOccurrenceField = value;
                    this.RaisePropertyChanged("LastOccurrence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MeetingRequestWasSent {
            get {
                return this.MeetingRequestWasSentField;
            }
            set {
                if ((this.MeetingRequestWasSentField.Equals(value) != true)) {
                    this.MeetingRequestWasSentField = value;
                    this.RaisePropertyChanged("MeetingRequestWasSent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeetingWorkspaceUrl {
            get {
                return this.MeetingWorkspaceUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.MeetingWorkspaceUrlField, value) != true)) {
                    this.MeetingWorkspaceUrlField = value;
                    this.RaisePropertyChanged("MeetingWorkspaceUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Bnhp.Office365.References.MeetingResponseType MyResponseType {
            get {
                return this.MyResponseTypeField;
            }
            set {
                if ((this.MyResponseTypeField.Equals(value) != true)) {
                    this.MyResponseTypeField = value;
                    this.RaisePropertyChanged("MyResponseType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NetShowUrl {
            get {
                return this.NetShowUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.NetShowUrlField, value) != true)) {
                    this.NetShowUrlField = value;
                    this.RaisePropertyChanged("NetShowUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Bnhp.Office365.References.Attendee[] OptionalAttendees {
            get {
                return this.OptionalAttendeesField;
            }
            set {
                if ((object.ReferenceEquals(this.OptionalAttendeesField, value) != true)) {
                    this.OptionalAttendeesField = value;
                    this.RaisePropertyChanged("OptionalAttendees");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Bnhp.Office365.References.Attendee Organizer {
            get {
                return this.OrganizerField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizerField, value) != true)) {
                    this.OrganizerField = value;
                    this.RaisePropertyChanged("Organizer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OriginalStart {
            get {
                return this.OriginalStartField;
            }
            set {
                if ((this.OriginalStartField.Equals(value) != true)) {
                    this.OriginalStartField = value;
                    this.RaisePropertyChanged("OriginalStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Bnhp.Office365.References.Recurrence Recurrence {
            get {
                return this.RecurrenceField;
            }
            set {
                if ((object.ReferenceEquals(this.RecurrenceField, value) != true)) {
                    this.RecurrenceField = value;
                    this.RaisePropertyChanged("Recurrence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReminderMinutesBeforeStart {
            get {
                return this.ReminderMinutesBeforeStartField;
            }
            set {
                if ((this.ReminderMinutesBeforeStartField.Equals(value) != true)) {
                    this.ReminderMinutesBeforeStartField = value;
                    this.RaisePropertyChanged("ReminderMinutesBeforeStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Bnhp.Office365.References.Attendee[] RequiredAttendees {
            get {
                return this.RequiredAttendeesField;
            }
            set {
                if ((object.ReferenceEquals(this.RequiredAttendeesField, value) != true)) {
                    this.RequiredAttendeesField = value;
                    this.RaisePropertyChanged("RequiredAttendees");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Bnhp.Office365.References.Attendee[] Resources {
            get {
                return this.ResourcesField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourcesField, value) != true)) {
                    this.ResourcesField = value;
                    this.RaisePropertyChanged("Resources");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RetentionDate {
            get {
                return this.RetentionDateField;
            }
            set {
                if ((this.RetentionDateField.Equals(value) != true)) {
                    this.RetentionDateField = value;
                    this.RaisePropertyChanged("RetentionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Start {
            get {
                return this.StartField;
            }
            set {
                if ((this.StartField.Equals(value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeZone {
            get {
                return this.TimeZoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeZoneField, value) != true)) {
                    this.TimeZoneField = value;
                    this.RaisePropertyChanged("TimeZone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string When {
            get {
                return this.WhenField;
            }
            set {
                if ((object.ReferenceEquals(this.WhenField, value) != true)) {
                    this.WhenField = value;
                    this.RaisePropertyChanged("When");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtendedProperty", Namespace="https://www.bankhapoalim.co.il/")]
    [System.SerializableAttribute()]
    public partial class ExtendedProperty : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Importance", Namespace="https://www.bankhapoalim.co.il/")]
    public enum Importance : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Low = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        High = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sensitivity", Namespace="https://www.bankhapoalim.co.il/")]
    public enum Sensitivity : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Personal = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Private = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Confidential = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OccurrenceInfo", Namespace="https://www.bankhapoalim.co.il/")]
    [System.SerializableAttribute()]
    public partial class OccurrenceInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime End {
            get {
                return this.EndField;
            }
            set {
                if ((this.EndField.Equals(value) != true)) {
                    this.EndField = value;
                    this.RaisePropertyChanged("End");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Start {
            get {
                return this.StartField;
            }
            set {
                if ((this.StartField.Equals(value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attendee", Namespace="https://www.bankhapoalim.co.il/")]
    [System.SerializableAttribute()]
    public partial class Attendee : Bnhp.Office365.References.EMailAddress {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<Bnhp.Office365.References.MeetingResponseType> ResponseTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Bnhp.Office365.References.MeetingResponseType> ResponseType {
            get {
                return this.ResponseTypeField;
            }
            set {
                if ((this.ResponseTypeField.Equals(value) != true)) {
                    this.ResponseTypeField = value;
                    this.RaisePropertyChanged("ResponseType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Recurrence", Namespace="https://www.bankhapoalim.co.il/")]
    [System.SerializableAttribute()]
    public partial class Recurrence : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumberOfOccurrencesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginalTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Bnhp.Office365.References.RecurrenceType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Interval {
            get {
                return this.IntervalField;
            }
            set {
                if ((this.IntervalField.Equals(value) != true)) {
                    this.IntervalField = value;
                    this.RaisePropertyChanged("Interval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumberOfOccurrences {
            get {
                return this.NumberOfOccurrencesField;
            }
            set {
                if ((this.NumberOfOccurrencesField.Equals(value) != true)) {
                    this.NumberOfOccurrencesField = value;
                    this.RaisePropertyChanged("NumberOfOccurrences");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalTypeName {
            get {
                return this.OriginalTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalTypeNameField, value) != true)) {
                    this.OriginalTypeNameField = value;
                    this.RaisePropertyChanged("OriginalTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Bnhp.Office365.References.RecurrenceType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MeetingResponseType", Namespace="https://www.bankhapoalim.co.il/")]
    public enum MeetingResponseType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Organizer = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tentative = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Accept = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Decline = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoResponseReceived = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EMailAddress", Namespace="https://www.bankhapoalim.co.il/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bnhp.Office365.References.Attendee))]
    public partial class EMailAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attachment", Namespace="https://www.bankhapoalim.co.il/")]
    [System.SerializableAttribute()]
    public partial class Attachment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentType {
            get {
                return this.ContentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentTypeField, value) != true)) {
                    this.ContentTypeField = value;
                    this.RaisePropertyChanged("ContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Size {
            get {
                return this.SizeField;
            }
            set {
                if ((this.SizeField.Equals(value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecurrenceType", Namespace="https://www.bankhapoalim.co.il/")]
    public enum RecurrenceType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Daily = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Weekly = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Monthly = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yearly = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MimeContent", Namespace="https://www.bankhapoalim.co.il/")]
    [System.SerializableAttribute()]
    public partial class MimeContent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CharacterSetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ContentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CharacterSet {
            get {
                return this.CharacterSetField;
            }
            set {
                if ((object.ReferenceEquals(this.CharacterSetField, value) != true)) {
                    this.CharacterSetField = value;
                    this.RaisePropertyChanged("CharacterSet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Change", Namespace="https://www.bankhapoalim.co.il/")]
    [System.SerializableAttribute()]
    public partial class Change : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Bnhp.Office365.References.ChangeType ChangeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Bnhp.Office365.References.ChangeType ChangeType {
            get {
                return this.ChangeTypeField;
            }
            set {
                if ((this.ChangeTypeField.Equals(value) != true)) {
                    this.ChangeTypeField = value;
                    this.RaisePropertyChanged("ChangeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FolderID {
            get {
                return this.FolderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FolderIDField, value) != true)) {
                    this.FolderIDField = value;
                    this.RaisePropertyChanged("FolderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemID {
            get {
                return this.ItemIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemIDField, value) != true)) {
                    this.ItemIDField = value;
                    this.RaisePropertyChanged("ItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeType", Namespace="https://www.bankhapoalim.co.il/")]
    public enum ChangeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Created = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Updated = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeStats", Namespace="https://www.bankhapoalim.co.il/")]
    [System.SerializableAttribute()]
    public partial class ChangeStats : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.bankhapoalim.co.il/", ConfigurationName="References.IEwsService")]
    public interface IEwsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/CreateAppointment", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/CreateAppointmentResponse")]
        string CreateAppointment(string email, Bnhp.Office365.References.Appointment appointment);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/CreateAppointment", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/CreateAppointmentResponse")]
        System.Threading.Tasks.Task<string> CreateAppointmentAsync(string email, Bnhp.Office365.References.Appointment appointment);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/FindAppointments", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/FindAppointmentsResponse")]
        string[] FindAppointments(string email, System.DateTime start, System.Nullable<System.DateTime> end, System.Nullable<int> maxResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/FindAppointments", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/FindAppointmentsResponse")]
        System.Threading.Tasks.Task<string[]> FindAppointmentsAsync(string email, System.DateTime start, System.Nullable<System.DateTime> end, System.Nullable<int> maxResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/GetAppointment", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/GetAppointmentResponse")]
        Bnhp.Office365.References.Appointment GetAppointment(string email, string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/GetAppointment", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/GetAppointmentResponse")]
        System.Threading.Tasks.Task<Bnhp.Office365.References.Appointment> GetAppointmentAsync(string email, string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/UpdateAppointment", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/UpdateAppointmentResponse")]
        bool UpdateAppointment(string email, Bnhp.Office365.References.Appointment appointment);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/UpdateAppointment", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/UpdateAppointmentResponse")]
        System.Threading.Tasks.Task<bool> UpdateAppointmentAsync(string email, Bnhp.Office365.References.Appointment appointment);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/CancelAppointment", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/CancelAppointmentResponse")]
        bool CancelAppointment(string email, string ID, string reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/CancelAppointment", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/CancelAppointmentResponse")]
        System.Threading.Tasks.Task<bool> CancelAppointmentAsync(string email, string ID, string reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/DeleteAppointment", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/DeleteAppointmentResponse")]
        bool DeleteAppointment(string email, string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/DeleteAppointment", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/DeleteAppointmentResponse")]
        System.Threading.Tasks.Task<bool> DeleteAppointmentAsync(string email, string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/AcceptAppointment", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/AcceptAppointmentResponse")]
        bool AcceptAppointment(string email, string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/AcceptAppointment", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/AcceptAppointmentResponse")]
        System.Threading.Tasks.Task<bool> AcceptAppointmentAsync(string email, string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/DeclineAppointment", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/DeclineAppointmentResponse")]
        bool DeclineAppointment(string email, string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/DeclineAppointment", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/DeclineAppointmentResponse")]
        System.Threading.Tasks.Task<bool> DeclineAppointmentAsync(string email, string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/CreateMessage", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/CreateMessageResponse")]
        string CreateMessage(string email, Bnhp.Office365.References.EMailMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/CreateMessage", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/CreateMessageResponse")]
        System.Threading.Tasks.Task<string> CreateMessageAsync(string email, Bnhp.Office365.References.EMailMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/AddAttachment", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/AddAttachmentResponse")]
        bool AddAttachment(string email, string ID, string name, byte[] content);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/AddAttachment", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/AddAttachmentResponse")]
        System.Threading.Tasks.Task<bool> AddAttachmentAsync(string email, string ID, string name, byte[] content);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/SendMessage", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/SendMessageResponse")]
        bool SendMessage(string email, string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/SendMessage", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/SendMessageResponse")]
        System.Threading.Tasks.Task<bool> SendMessageAsync(string email, string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/FindMessages", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/FindMessagesResponse")]
        string[] FindMessages(string email, System.Nullable<int> pageSize, System.Nullable<int> offset);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/FindMessages", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/FindMessagesResponse")]
        System.Threading.Tasks.Task<string[]> FindMessagesAsync(string email, System.Nullable<int> pageSize, System.Nullable<int> offset);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/GetMessage", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/GetMessageResponse")]
        Bnhp.Office365.References.EMailMessage GetMessage(string email, string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/GetMessage", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/GetMessageResponse")]
        System.Threading.Tasks.Task<Bnhp.Office365.References.EMailMessage> GetMessageAsync(string email, string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/GetAttachmentByName", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/GetAttachmentByNameResponse")]
        byte[] GetAttachmentByName(string email, string ID, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/GetAttachmentByName", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/GetAttachmentByNameResponse")]
        System.Threading.Tasks.Task<byte[]> GetAttachmentByNameAsync(string email, string ID, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/GetAttachmentByIndex", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/GetAttachmentByIndexResponse")]
        byte[] GetAttachmentByIndex(string email, string ID, int index);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/GetAttachmentByIndex", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/GetAttachmentByIndexResponse")]
        System.Threading.Tasks.Task<byte[]> GetAttachmentByIndexAsync(string email, string ID, int index);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/GetMessageContent", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/GetMessageContentResponse")]
        Bnhp.Office365.References.MimeContent GetMessageContent(string email, string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/GetMessageContent", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/GetMessageContentResponse")]
        System.Threading.Tasks.Task<Bnhp.Office365.References.MimeContent> GetMessageContentAsync(string email, string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/DeleteMessage", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/DeleteMessageResponse")]
        bool DeleteMessage(string email, string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/DeleteMessage", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/DeleteMessageResponse")]
        System.Threading.Tasks.Task<bool> DeleteMessageAsync(string email, string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/MoveTo", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/MoveToResponse")]
        bool MoveTo(string email, string ID, string folder);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/MoveTo", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/MoveToResponse")]
        System.Threading.Tasks.Task<bool> MoveToAsync(string email, string ID, string folder);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/CopyTo", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/CopyToResponse")]
        bool CopyTo(string email, string ID, string folder);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/CopyTo", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/CopyToResponse")]
        System.Threading.Tasks.Task<bool> CopyToAsync(string email, string ID, string folder);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/Notification", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/NotificationResponse")]
        bool Notification(string email, string ID, string changeType);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/Notification", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/NotificationResponse")]
        System.Threading.Tasks.Task<bool> NotificationAsync(string email, string ID, string changeType);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/GetChanges", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/GetChangesResponse")]
        Bnhp.Office365.References.Change[] GetChanges(string systemName, string email, string folderID, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate, System.Nullable<int> skip, System.Nullable<int> take);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/GetChanges", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/GetChangesResponse")]
        System.Threading.Tasks.Task<Bnhp.Office365.References.Change[]> GetChangesAsync(string systemName, string email, string folderID, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate, System.Nullable<int> skip, System.Nullable<int> take);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/GetChangeStats", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/GetChangeStatsResponse")]
        Bnhp.Office365.References.ChangeStats[] GetChangeStats(string systemName, string email, string folderID, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate, System.Nullable<int> skip, System.Nullable<int> take);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.bankhapoalim.co.il/IEwsService/GetChangeStats", ReplyAction="https://www.bankhapoalim.co.il/IEwsService/GetChangeStatsResponse")]
        System.Threading.Tasks.Task<Bnhp.Office365.References.ChangeStats[]> GetChangeStatsAsync(string systemName, string email, string folderID, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate, System.Nullable<int> skip, System.Nullable<int> take);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEwsServiceChannel : Bnhp.Office365.References.IEwsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EwsServiceClient : System.ServiceModel.ClientBase<Bnhp.Office365.References.IEwsService>, Bnhp.Office365.References.IEwsService {
        
        public EwsServiceClient() {
        }
        
        public EwsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EwsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EwsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EwsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CreateAppointment(string email, Bnhp.Office365.References.Appointment appointment) {
            return base.Channel.CreateAppointment(email, appointment);
        }
        
        public System.Threading.Tasks.Task<string> CreateAppointmentAsync(string email, Bnhp.Office365.References.Appointment appointment) {
            return base.Channel.CreateAppointmentAsync(email, appointment);
        }
        
        public string[] FindAppointments(string email, System.DateTime start, System.Nullable<System.DateTime> end, System.Nullable<int> maxResults) {
            return base.Channel.FindAppointments(email, start, end, maxResults);
        }
        
        public System.Threading.Tasks.Task<string[]> FindAppointmentsAsync(string email, System.DateTime start, System.Nullable<System.DateTime> end, System.Nullable<int> maxResults) {
            return base.Channel.FindAppointmentsAsync(email, start, end, maxResults);
        }
        
        public Bnhp.Office365.References.Appointment GetAppointment(string email, string ID) {
            return base.Channel.GetAppointment(email, ID);
        }
        
        public System.Threading.Tasks.Task<Bnhp.Office365.References.Appointment> GetAppointmentAsync(string email, string ID) {
            return base.Channel.GetAppointmentAsync(email, ID);
        }
        
        public bool UpdateAppointment(string email, Bnhp.Office365.References.Appointment appointment) {
            return base.Channel.UpdateAppointment(email, appointment);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAppointmentAsync(string email, Bnhp.Office365.References.Appointment appointment) {
            return base.Channel.UpdateAppointmentAsync(email, appointment);
        }
        
        public bool CancelAppointment(string email, string ID, string reason) {
            return base.Channel.CancelAppointment(email, ID, reason);
        }
        
        public System.Threading.Tasks.Task<bool> CancelAppointmentAsync(string email, string ID, string reason) {
            return base.Channel.CancelAppointmentAsync(email, ID, reason);
        }
        
        public bool DeleteAppointment(string email, string ID) {
            return base.Channel.DeleteAppointment(email, ID);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAppointmentAsync(string email, string ID) {
            return base.Channel.DeleteAppointmentAsync(email, ID);
        }
        
        public bool AcceptAppointment(string email, string ID) {
            return base.Channel.AcceptAppointment(email, ID);
        }
        
        public System.Threading.Tasks.Task<bool> AcceptAppointmentAsync(string email, string ID) {
            return base.Channel.AcceptAppointmentAsync(email, ID);
        }
        
        public bool DeclineAppointment(string email, string ID) {
            return base.Channel.DeclineAppointment(email, ID);
        }
        
        public System.Threading.Tasks.Task<bool> DeclineAppointmentAsync(string email, string ID) {
            return base.Channel.DeclineAppointmentAsync(email, ID);
        }
        
        public string CreateMessage(string email, Bnhp.Office365.References.EMailMessage message) {
            return base.Channel.CreateMessage(email, message);
        }
        
        public System.Threading.Tasks.Task<string> CreateMessageAsync(string email, Bnhp.Office365.References.EMailMessage message) {
            return base.Channel.CreateMessageAsync(email, message);
        }
        
        public bool AddAttachment(string email, string ID, string name, byte[] content) {
            return base.Channel.AddAttachment(email, ID, name, content);
        }
        
        public System.Threading.Tasks.Task<bool> AddAttachmentAsync(string email, string ID, string name, byte[] content) {
            return base.Channel.AddAttachmentAsync(email, ID, name, content);
        }
        
        public bool SendMessage(string email, string ID) {
            return base.Channel.SendMessage(email, ID);
        }
        
        public System.Threading.Tasks.Task<bool> SendMessageAsync(string email, string ID) {
            return base.Channel.SendMessageAsync(email, ID);
        }
        
        public string[] FindMessages(string email, System.Nullable<int> pageSize, System.Nullable<int> offset) {
            return base.Channel.FindMessages(email, pageSize, offset);
        }
        
        public System.Threading.Tasks.Task<string[]> FindMessagesAsync(string email, System.Nullable<int> pageSize, System.Nullable<int> offset) {
            return base.Channel.FindMessagesAsync(email, pageSize, offset);
        }
        
        public Bnhp.Office365.References.EMailMessage GetMessage(string email, string ID) {
            return base.Channel.GetMessage(email, ID);
        }
        
        public System.Threading.Tasks.Task<Bnhp.Office365.References.EMailMessage> GetMessageAsync(string email, string ID) {
            return base.Channel.GetMessageAsync(email, ID);
        }
        
        public byte[] GetAttachmentByName(string email, string ID, string name) {
            return base.Channel.GetAttachmentByName(email, ID, name);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetAttachmentByNameAsync(string email, string ID, string name) {
            return base.Channel.GetAttachmentByNameAsync(email, ID, name);
        }
        
        public byte[] GetAttachmentByIndex(string email, string ID, int index) {
            return base.Channel.GetAttachmentByIndex(email, ID, index);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetAttachmentByIndexAsync(string email, string ID, int index) {
            return base.Channel.GetAttachmentByIndexAsync(email, ID, index);
        }
        
        public Bnhp.Office365.References.MimeContent GetMessageContent(string email, string ID) {
            return base.Channel.GetMessageContent(email, ID);
        }
        
        public System.Threading.Tasks.Task<Bnhp.Office365.References.MimeContent> GetMessageContentAsync(string email, string ID) {
            return base.Channel.GetMessageContentAsync(email, ID);
        }
        
        public bool DeleteMessage(string email, string ID) {
            return base.Channel.DeleteMessage(email, ID);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteMessageAsync(string email, string ID) {
            return base.Channel.DeleteMessageAsync(email, ID);
        }
        
        public bool MoveTo(string email, string ID, string folder) {
            return base.Channel.MoveTo(email, ID, folder);
        }
        
        public System.Threading.Tasks.Task<bool> MoveToAsync(string email, string ID, string folder) {
            return base.Channel.MoveToAsync(email, ID, folder);
        }
        
        public bool CopyTo(string email, string ID, string folder) {
            return base.Channel.CopyTo(email, ID, folder);
        }
        
        public System.Threading.Tasks.Task<bool> CopyToAsync(string email, string ID, string folder) {
            return base.Channel.CopyToAsync(email, ID, folder);
        }
        
        public bool Notification(string email, string ID, string changeType) {
            return base.Channel.Notification(email, ID, changeType);
        }
        
        public System.Threading.Tasks.Task<bool> NotificationAsync(string email, string ID, string changeType) {
            return base.Channel.NotificationAsync(email, ID, changeType);
        }
        
        public Bnhp.Office365.References.Change[] GetChanges(string systemName, string email, string folderID, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate, System.Nullable<int> skip, System.Nullable<int> take) {
            return base.Channel.GetChanges(systemName, email, folderID, startDate, endDate, skip, take);
        }
        
        public System.Threading.Tasks.Task<Bnhp.Office365.References.Change[]> GetChangesAsync(string systemName, string email, string folderID, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate, System.Nullable<int> skip, System.Nullable<int> take) {
            return base.Channel.GetChangesAsync(systemName, email, folderID, startDate, endDate, skip, take);
        }
        
        public Bnhp.Office365.References.ChangeStats[] GetChangeStats(string systemName, string email, string folderID, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate, System.Nullable<int> skip, System.Nullable<int> take) {
            return base.Channel.GetChangeStats(systemName, email, folderID, startDate, endDate, skip, take);
        }
        
        public System.Threading.Tasks.Task<Bnhp.Office365.References.ChangeStats[]> GetChangeStatsAsync(string systemName, string email, string folderID, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate, System.Nullable<int> skip, System.Nullable<int> take) {
            return base.Channel.GetChangeStatsAsync(systemName, email, folderID, startDate, endDate, skip, take);
        }
    }
}
