
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Bnhp.Office365
{

using System;
    using System.Collections.Generic;
    
public partial class BankNotification
{

    public System.DateTime Timestamp { get; set; }

    public string ItemID { get; set; }

    public string Email { get; set; }

    public string ChangeType { get; set; }

}

}
