
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Bnhp.Office365
{

using System;
    using System.Collections.Generic;
    
public partial class BankSystem
{

    public BankSystem()
    {

        this.BankSystemMailboxes = new HashSet<BankSystemMailbox>();

        this.BankSystemNotifications = new HashSet<BankSystemNotification>();

        this.BankSystemRights = new HashSet<BankSystemRight>();

    }


    public string GroupName { get; set; }

    public string Description { get; set; }

    public bool Local { get; set; }

    public string CallbackURL { get; set; }



    public virtual ICollection<BankSystemMailbox> BankSystemMailboxes { get; set; }

    public virtual ICollection<BankSystemNotification> BankSystemNotifications { get; set; }

    public virtual ICollection<BankSystemRight> BankSystemRights { get; set; }

}

}
