
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Bnhp.Office365
{

using System;
    using System.Collections.Generic;
    
public partial class BankSystemMailbox
{

    public int SystemID { get; set; }

    public string Email { get; set; }



    public virtual BankSystem BankSystem { get; set; }

}

}
