
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Bnhp.Office365
{

using System;
    using System.Collections.Generic;
    
public partial class BankMailbox
{

    public BankMailbox()
    {

        this.BankNotifications = new HashSet<BankNotification>();

        this.WorkTables = new HashSet<WorkTable>();

    }


    public string mailAddress { get; set; }

    public string userName { get; set; }

    public string groupingInformation { get; set; }

    public bool notifyOnNewMails { get; set; }

    public bool notifyOnNewAppointments { get; set; }

    public string ewsUrl { get; set; }

    public string calendarSyncStatus { get; set; }

    public string inboxSyncStatus { get; set; }

    public string managingServer { get; set; }

    public bool Invalid { get; set; }



    public virtual ICollection<BankNotification> BankNotifications { get; set; }

    public virtual ICollection<WorkTable> WorkTables { get; set; }

}

}
