
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Bnhp.Office365
{

using System;
    using System.Collections.Generic;
    
public partial class SystemManager
{

    public SystemManager()
    {

        this.BankSystems = new HashSet<BankSystem>();

    }


    public int systemManagerId { get; set; }

    public string name { get; set; }

    public string phone { get; set; }

    public string mail { get; set; }



    public virtual ICollection<BankSystem> BankSystems { get; set; }

}

}
