
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Bnhp.Office365
{

using System;
    using System.Collections.Generic;
    
public partial class WorkTable
{

    public string mailAddress { get; set; }

    public int systemId { get; set; }

    public bool notifyOnNewMails { get; set; }

    public bool notifyOnNewAppointments { get; set; }



    public virtual BankMailbox BankMailbox { get; set; }

    public virtual BankSystem BankSystem { get; set; }

}

}
