//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mailer.Models
{
    using System;
    
    public partial class BankUnit
    {
        public Nullable<short> BranchID { get; set; }
        public string HierarchyID { get; set; }
        public string BranchName { get; set; }
        public string BranchNameEN { get; set; }
        public string GroupName { get; set; }
        public string DepartmentName { get; set; }
        public string AdministrationName { get; set; }
    }
}
