//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mailer.Models
{
    using System;
    
    public partial class ExtendedRecipient
    {
        public string ItemName { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<short> BranchID { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string FirstNameEN { get; set; }
        public string SecondNameEN { get; set; }
        public string EMail { get; set; }
        public string Title { get; set; }
        public string HierarchyID { get; set; }
        public string BranchName { get; set; }
        public string BranchNameEN { get; set; }
        public string GroupName { get; set; }
        public string DepartmentName { get; set; }
        public string AdministrationName { get; set; }
    }
}
