//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bnhp.Office365.RulesServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rule", Namespace="http://schemas.datacontract.org/2004/07/Bnhp.Office365")]
    [System.SerializableAttribute()]
    public partial class Rule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParamsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Action {
            get {
                return this.ActionField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionField, value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Params {
            get {
                return this.ParamsField;
            }
            set {
                if ((object.ReferenceEquals(this.ParamsField, value) != true)) {
                    this.ParamsField = value;
                    this.RaisePropertyChanged("Params");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RulesServiceReference.IRulesService")]
    public interface IRulesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRulesService/GetRules", ReplyAction="http://tempuri.org/IRulesService/GetRulesResponse")]
        Bnhp.Office365.RulesServiceReference.Rule[] GetRules(string systemName, string mailbox);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRulesService/GetRules", ReplyAction="http://tempuri.org/IRulesService/GetRulesResponse")]
        System.Threading.Tasks.Task<Bnhp.Office365.RulesServiceReference.Rule[]> GetRulesAsync(string systemName, string mailbox);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRulesService/GetLastCheck", ReplyAction="http://tempuri.org/IRulesService/GetLastCheckResponse")]
        System.Nullable<System.DateTime> GetLastCheck(string systemName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRulesService/GetLastCheck", ReplyAction="http://tempuri.org/IRulesService/GetLastCheckResponse")]
        System.Threading.Tasks.Task<System.Nullable<System.DateTime>> GetLastCheckAsync(string systemName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRulesService/UpdateLastCheck", ReplyAction="http://tempuri.org/IRulesService/UpdateLastCheckResponse")]
        void UpdateLastCheck(string systemName, System.DateTime timestamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRulesService/UpdateLastCheck", ReplyAction="http://tempuri.org/IRulesService/UpdateLastCheckResponse")]
        System.Threading.Tasks.Task UpdateLastCheckAsync(string systemName, System.DateTime timestamp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRulesServiceChannel : Bnhp.Office365.RulesServiceReference.IRulesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RulesServiceClient : System.ServiceModel.ClientBase<Bnhp.Office365.RulesServiceReference.IRulesService>, Bnhp.Office365.RulesServiceReference.IRulesService {
        
        public RulesServiceClient() {
        }
        
        public RulesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RulesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RulesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RulesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Bnhp.Office365.RulesServiceReference.Rule[] GetRules(string systemName, string mailbox) {
            return base.Channel.GetRules(systemName, mailbox);
        }
        
        public System.Threading.Tasks.Task<Bnhp.Office365.RulesServiceReference.Rule[]> GetRulesAsync(string systemName, string mailbox) {
            return base.Channel.GetRulesAsync(systemName, mailbox);
        }
        
        public System.Nullable<System.DateTime> GetLastCheck(string systemName) {
            return base.Channel.GetLastCheck(systemName);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<System.DateTime>> GetLastCheckAsync(string systemName) {
            return base.Channel.GetLastCheckAsync(systemName);
        }
        
        public void UpdateLastCheck(string systemName, System.DateTime timestamp) {
            base.Channel.UpdateLastCheck(systemName, timestamp);
        }
        
        public System.Threading.Tasks.Task UpdateLastCheckAsync(string systemName, System.DateTime timestamp) {
            return base.Channel.UpdateLastCheckAsync(systemName, timestamp);
        }
    }
}
